### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AshiquK** [remarkablemark/react-dom-core#1]
ERROR in ./~/react-dom-core/lib/ReactDebugTool.js
Module not found: Error: Cannot resolve module 'react/lib/ReactComponentTreeHook' in /home/aaa/bbb/node_modules/react-dom-core/lib
 @ ./~/react-dom-core/lib/ReactDebugTool.js 14:29-72

**Comment by remarkablemark** [comment]
@AshiquK Can you outline the steps to reproduce this error?

**Comment by AshiquK** [comment]
import { DOMProperty } from 'react-dom-core/lib/ReactInjection';
.....

DOMProperty.injectDOMPropertyConfig(HTMLDOMPropertyConfig);
.....

**Comment by remarkablemark** [comment]
@AshiquK The issue turned out to be that `react` changed the directory structure (`lib/` is no longer exposed).

The fix was to add `react@15` as a dependency of this package.

Please install the latest version of `react-dom-core` and let me know if this resolves your issue.
