### ISSUE TITLE
Not needed peerDependencies

### ISSUE THREAD

**Issue by RomanGotsiy** [remarkablemark/react-dom-core#3]
I get a bunch of `peerDependencies` warnings when installing a package with this pacakge as a dep:

```
warning "gatsby-plugin-favicon > html-react-parser > react-dom-core@0.0.3" has unmet peer dependency "fbjs@*".
warning "gatsby-plugin-favicon > html-react-parser > react-dom-core@0.0.3" has unmet peer dependency "object-assign@*".
```

I've looked in and found out that `fbjs` and `object-assign` dependencies are the actual dependencies of React@15: https://github.com/facebook/react/blob/15-stable/packages/react-dom/package.json#L16-L18 so there is no point to specifying them as `peerDependencies` of this package.

Could you please remove it? These warnings drives me mad 😄

**Comment by remarkablemark** [comment]
Good point. Would you like to make a pull request?

**Comment by RomanGotsiy** [comment]
Done: https://github.com/remarkablemark/react-dom-core/pull/4

Also, update please html-react-parser to the new version. No hurry though.

Thanks for the quick response!

**Comment by remarkablemark** [comment]
Thanks for making the PR @RomanGotsiy, I'll make a release tonight and update `html-react-parser`
