### ISSUE TITLE
doc(react-property): broken link for DOMProperty

### ISSUE THREAD

**Issue by kumavis** [remarkablemark/react-dom-core#86]
readme links to "DOMProperty" but this file was moved [then deleted here](https://github.com/facebook/react/commit/eeabb7312f509eb2094452a4389646000ea8ea14#diff-67b481b96d526280780f010dfd192761f2d1f6dc812e3015020a7986501d2eba)

[here is the last version](https://github.com/facebook/react/blob/0ba4d7b0d80d942dc8f074f7ce0536e6b2559fbf/packages/react-dom-bindings/src/shared/DOMProperty.js) of the referenced file.

There may be a more suitable replacement file to reference as a result of [this refactor](https://github.com/facebook/react/pull/26546)

**Comment by remarkablemark** [comment]
Closed in #85
